/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.2 at Wed Sep 19 18:18:41 2018. */

#include "bdd_pb2.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t bdd_MetaData_bddVersion_default = 1u;


const pb_field_t bdd_MetaData_fields[7] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, bdd_MetaData, date, date, 0),
    PB_FIELD(  2, FIXED32 , REQUIRED, STATIC  , OTHER, bdd_MetaData, version, date, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, bdd_MetaData, author, version, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, bdd_MetaData, organization, author, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, bdd_MetaData, company, organization, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_MetaData, bddVersion, company, &bdd_MetaData_bddVersion_default),
    PB_LAST_FIELD
};

const pb_field_t bdd_CustomNodeIdSettings_fields[12] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_CustomNodeIdSettings, bCustomNodeIdAuth, bCustomNodeIdAuth, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, bReadFrmMemory, bCustomNodeIdAuth, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, bReadFrmCommCh, bReadFrmMemory, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nDeviceAddr, bReadFrmCommCh, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nNodeId, nDeviceAddr, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nNodeIdLength, nNodeId, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nReadMemAddrWidth, nNodeIdLength, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nReadMemAddr, nReadMemAddrWidth, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, bReadGpioPins, nReadMemAddr, 0),
    PB_FIELD( 10, UINT32  , REPEATED, STATIC  , OTHER, bdd_CustomNodeIdSettings, aGpio, bReadGpioPins, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CustomNodeIdSettings, nTimeOut, aGpio, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_NodeDescriptor_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, bdd_NodeDescriptor, vendor, vendor, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, bdd_NodeDescriptor, product, vendor, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, bdd_NodeDescriptor, version, product, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_NodeDescriptor, oCustomNodeIdSettings, version, &bdd_CustomNodeIdSettings_fields),
    PB_LAST_FIELD
};

const pb_field_t bdd_CtrlRegs_fields[11] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_CtrlRegs, bcdnslots, bcdnslots, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, ldnslots, bcdnslots, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, lupslots, ldnslots, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, dnslots, lupslots, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, upslots, dnslots, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, respcycs, upslots, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, slotfmt, respcycs, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, suscfg, slotfmt, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, datctl, suscfg, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_CtrlRegs, control, datctl, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_IntRegs_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_IntRegs, intmsk0, intmsk0, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_IntRegs, intmsk1, intmsk0, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_IntRegs, intmsk2, intmsk1, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_IntRegs, becctl, intmsk2, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_TuningRegs_fields[6] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_TuningRegs, vregctl, vregctl, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_TuningRegs, txactl, vregctl, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_TuningRegs, rxactl, txactl, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_TuningRegs, txbctl, rxactl, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_TuningRegs, rxbctl, txbctl, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_I2cI2sRegs_fields[15] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_I2cI2sRegs, i2ccfg, i2ccfg, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, pllctl, i2ccfg, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2sgcfg, pllctl, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2scfg, i2sgcfg, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2srate, i2scfg, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2stxoffset, i2srate, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2srxoffset, i2stxoffset, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, syncoffset, i2srxoffset, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, pdmctl, syncoffset, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, errmgmt, pdmctl, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2srrate, errmgmt, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2srrctl, i2srrate, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, i2srrsoffs, i2srrctl, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_I2cI2sRegs, pdmctl2, i2srrsoffs, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_PinIoRegs_fields[10] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_PinIoRegs, clkcfg, clkcfg, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, gpiooen, clkcfg, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, gpioien, gpiooen, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, pinten, gpioien, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, pintinv, pinten, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, pincfg, pintinv, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, gpiodat, pincfg, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, clk1cfg, gpiodat, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_PinIoRegs, clk2cfg, clk1cfg, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_DataSlotEnhancementRegs_fields[11] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_DataSlotEnhancementRegs, upmask0, upmask0, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, upmask1, upmask0, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, upmask2, upmask1, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, upmask3, upmask2, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, upoffset, upmask3, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, dnmask0, upoffset, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, dnmask1, dnmask0, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, dnmask2, dnmask1, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, dnmask3, dnmask2, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_DataSlotEnhancementRegs, dnoffset, dnmask3, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_GpioDRegs_fields[12] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_GpioDRegs, gpioden, gpioden, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod0msk, gpioden, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod1msk, gpiod0msk, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod2msk, gpiod1msk, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod3msk, gpiod2msk, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod4msk, gpiod3msk, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod5msk, gpiod4msk, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod6msk, gpiod5msk, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiod7msk, gpiod6msk, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpioddat, gpiod7msk, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_GpioDRegs, gpiodinv, gpioddat, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_MailboxRegs_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, bdd_MailboxRegs, mbox0ctl, mbox0ctl, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, bdd_MailboxRegs, mbox1ctl, mbox0ctl, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_Stream_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, bdd_Stream, name, name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Stream, sampleRate, name, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Stream, sampleRateMultiplier, sampleRate, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Stream, numChans, sampleRateMultiplier, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_Node_fields[17] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, bdd_Node, nodeType, nodeType, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, bdd_Node, ctrlRegs, nodeType, &bdd_CtrlRegs_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_Node, intRegs, ctrlRegs, &bdd_IntRegs_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_Node, tuningRegs, intRegs, &bdd_TuningRegs_fields),
    PB_FIELD(  5, MESSAGE , REQUIRED, STATIC  , OTHER, bdd_Node, i2cI2sRegs, tuningRegs, &bdd_I2cI2sRegs_fields),
    PB_FIELD(  6, MESSAGE , REQUIRED, STATIC  , OTHER, bdd_Node, pinIoRegs, i2cI2sRegs, &bdd_PinIoRegs_fields),
    PB_FIELD(  7, BOOL    , REQUIRED, STATIC  , OTHER, bdd_Node, ignEeprom, pinIoRegs, 0),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, bdd_Node, verifyNodeDescr, ignEeprom, 0),
    PB_FIELD(  9, MESSAGE , REQUIRED, STATIC  , OTHER, bdd_Node, nodeDescr, verifyNodeDescr, &bdd_NodeDescriptor_fields),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Node, downstreamBcastCnt, nodeDescr, 0),
    PB_FIELD( 11, UINT32  , REPEATED, STATIC  , OTHER, bdd_Node, downstream, downstreamBcastCnt, 0),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Node, upstreamBcastCnt, downstream, 0),
    PB_FIELD( 13, UINT32  , REPEATED, STATIC  , OTHER, bdd_Node, upstream, upstreamBcastCnt, 0),
    PB_FIELD( 14, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_Node, slotEnh, upstream, &bdd_DataSlotEnhancementRegs_fields),
    PB_FIELD( 15, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_Node, gpioDist, slotEnh, &bdd_GpioDRegs_fields),
    PB_FIELD( 16, MESSAGE , OPTIONAL, STATIC  , OTHER, bdd_Node, mbox, gpioDist, &bdd_MailboxRegs_fields),
    PB_LAST_FIELD
};

const pb_field_t bdd_NetworkPolicy_fields[7] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, bdd_NetworkPolicy, discoveryMode, discoveryMode, 0),
    PB_FIELD(  2, ENUM    , REQUIRED, STATIC  , OTHER, bdd_NetworkPolicy, cfgMethod, discoveryMode, 0),
    PB_FIELD(  3, ENUM    , REQUIRED, STATIC  , OTHER, bdd_NetworkPolicy, cfgPriority, cfgMethod, 0),
    PB_FIELD(  4, ENUM    , REQUIRED, STATIC  , OTHER, bdd_NetworkPolicy, cfgErrPolicy, cfgPriority, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, bdd_NetworkPolicy, has_common_SSSettings, cfgErrPolicy, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, bdd_NetworkPolicy, discoveryStartDelay, has_common_SSSettings, 0),
    PB_LAST_FIELD
};

const pb_field_t bdd_Network_fields[7] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, bdd_Network, metaData, metaData, &bdd_MetaData_fields),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Network, masterAddr, metaData, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, bdd_Network, policy, masterAddr, &bdd_NetworkPolicy_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, bdd_Network, nodes, policy, &bdd_Node_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, bdd_Network, streams, nodes, &bdd_Stream_fields),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, bdd_Network, sampleRate, streams, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(bdd_NodeDescriptor, oCustomNodeIdSettings) < 65536 && pb_membersize(bdd_Node, ctrlRegs) < 65536 && pb_membersize(bdd_Node, intRegs) < 65536 && pb_membersize(bdd_Node, tuningRegs) < 65536 && pb_membersize(bdd_Node, i2cI2sRegs) < 65536 && pb_membersize(bdd_Node, pinIoRegs) < 65536 && pb_membersize(bdd_Node, nodeDescr) < 65536 && pb_membersize(bdd_Node, slotEnh) < 65536 && pb_membersize(bdd_Node, gpioDist) < 65536 && pb_membersize(bdd_Node, mbox) < 65536 && pb_membersize(bdd_Network, metaData) < 65536 && pb_membersize(bdd_Network, policy) < 65536 && pb_membersize(bdd_Network, nodes[0]) < 65536 && pb_membersize(bdd_Network, streams[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_bdd_MetaData_bdd_CustomNodeIdSettings_bdd_NodeDescriptor_bdd_CtrlRegs_bdd_IntRegs_bdd_TuningRegs_bdd_I2cI2sRegs_bdd_PinIoRegs_bdd_DataSlotEnhancementRegs_bdd_GpioDRegs_bdd_MailboxRegs_bdd_Stream_bdd_Node_bdd_NetworkPolicy_bdd_Network)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(bdd_NodeDescriptor, oCustomNodeIdSettings) < 256 && pb_membersize(bdd_Node, ctrlRegs) < 256 && pb_membersize(bdd_Node, intRegs) < 256 && pb_membersize(bdd_Node, tuningRegs) < 256 && pb_membersize(bdd_Node, i2cI2sRegs) < 256 && pb_membersize(bdd_Node, pinIoRegs) < 256 && pb_membersize(bdd_Node, nodeDescr) < 256 && pb_membersize(bdd_Node, slotEnh) < 256 && pb_membersize(bdd_Node, gpioDist) < 256 && pb_membersize(bdd_Node, mbox) < 256 && pb_membersize(bdd_Network, metaData) < 256 && pb_membersize(bdd_Network, policy) < 256 && pb_membersize(bdd_Network, nodes[0]) < 256 && pb_membersize(bdd_Network, streams[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_bdd_MetaData_bdd_CustomNodeIdSettings_bdd_NodeDescriptor_bdd_CtrlRegs_bdd_IntRegs_bdd_TuningRegs_bdd_I2cI2sRegs_bdd_PinIoRegs_bdd_DataSlotEnhancementRegs_bdd_GpioDRegs_bdd_MailboxRegs_bdd_Stream_bdd_Node_bdd_NetworkPolicy_bdd_Network)
#endif


