/**
 * Copyright (c) 2021 - Analog Devices Inc. All Rights Reserved.
 * This software is proprietary and confidential to Analog Devices, Inc.
 * and its licensors.
 *
 * This software is subject to the terms and conditions of the license set
 * forth in the project LICENSE file. Downloading, reproducing, distributing or
 * otherwise using the software constitutes acceptance of the license. The
 * software may not be used except as expressly authorized under the license.
 */

#include "twi_simple.h"

#include "registers_adau1761.h"
#include "adau1761.h"

typedef struct
{
    uint8_t *data_tx_buffer;
    uint16_t *data_num_bytes;
    uint16_t total_lines;
    bool ignore_first_byte_of_init_file;
} BM_ADAU_DEVICE_INIT_DATA;

// ADAU1761 Master I2S/50% 8 Channel Configuration
uint8_t ADAU1761_8ch_i2s_master_TxBuffer[] = {
    #include "TxBuffer_ADAU1761.dat"
};

uint16_t ADAU1761_8ch_i2s_master_NumBytes[] = {
    #include "NumBytes_ADAU1761.dat"
};

BM_ADAU_DEVICE_INIT_DATA adau1761_8ch_i2s_master = {
    .data_tx_buffer = ADAU1761_8ch_i2s_master_TxBuffer,
    .data_num_bytes = ADAU1761_8ch_i2s_master_NumBytes,
    .total_lines =
        sizeof(ADAU1761_8ch_i2s_master_NumBytes) /
            sizeof(ADAU1761_8ch_i2s_master_NumBytes[0]),
    .ignore_first_byte_of_init_file = false
};

/**
 * @brief      The SigmaStudio tools can dump a set of configuration files for
 *             easy device set up via Action -> Export System Files.  Amongst
 *             these files will be a length and a data file that need to be
 *             imported (See the ADAU testing code for an example).  This
 *             typically starts the ADAU1761 DSP at the end of the loading
 *             process so device set up becomes incredibly simple.
 *
 * @param      adau_device Pointer to the instance of this driver
 * @param      values      The values
 * @param      lengths     The lengths
 * @param[in]  total_lines  The total lines
 *
 * @return     { description_of_the_return_value }
 */
BM_ADAU_RESULT adau_load_bulk_reg_file(
    sTWI *twi, uint8_t adau_address,
    BM_ADAU_DEVICE_INIT_DATA *adau_init_data,
    bool ignore_first_byte_of_init_file)
{
    int i;
    uint16_t length;
    uint8_t *values = adau_init_data->data_tx_buffer;
    uint16_t *lengths = adau_init_data->data_num_bytes;
    uint16_t total_lines = adau_init_data->total_lines;
    TWI_SIMPLE_RESULT twiResult;

    for (i = 0; i < total_lines; i++) {

        length = *lengths++;

        // Some init files generated by SigmaStudio have an extra address byte which is zero - we ignore these
        if (ignore_first_byte_of_init_file) {
            length -= 1;
            values++;
        }

        // Look for any corrupted values in the initialization
        if (length > 10000 || length == 0) {
            return ADAU_CORRUPT_INIT_FILE;
        }
        else {
            twiResult = twi_write(twi, adau_address, values, length);
        }

        // If we're programming the ADAU1761
        if (*(values + 0) == 0x40 && *(values + 1) == 0x02 && length == 8) {
            uint8_t pllLock = 0;

            uint16_t timeout = 10000;
            uint8_t addr[2] = { ADAU1761_REG_PLL_CONTROL_0 >> 8, ADAU1761_REG_PLL_CONTROL_0 & 0xff};

            while (timeout-- && !(pllLock & 0x2)) {
                uint8_t pllvalues[6];

                /*
                 * The control register in the ADAU1761 which contains the PLL lock bit needs to
                 * be read as a group of 6 registers.  The PLL lock bit is in the last register.
                 */
                twiResult = twi_writeRead(
                    twi, adau_address, addr, 2, pllvalues, sizeof(pllvalues)
                );
                pllLock = pllvalues[5];
            }
            if (timeout == 0) return ADAU_PLL_LOCK_TIMEOUT_ERROR;
        }

        // Update pointer
        values += length;
    }

    return ADAU_SUCCESS;
}

BM_ADAU_RESULT init_adau1761(sTWI *twi, uint8_t adau_address)
{
    BM_ADAU_RESULT result;

    result = adau_load_bulk_reg_file(
        twi, adau_address, &adau1761_8ch_i2s_master, false
    );

    return(result);
}
